import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider"
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { ClientOnly, Skeleton } from "@chakra-ui/react";
import { AppKit } from "../context/appkit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <ClientOnly fallback={<Skeleton boxSize="8" />}>
            <Header />
            <AppKit>
              {children}
            </AppKit>
            <Footer />
          </ClientOnly>
        </Provider>
      </body>
    </html>
  );
}